### PR TITLE
Add documentation for setting up direct ethernet connection

### PR DESCRIPTION
**Pull request by mhfowler**
Today got direct ethernet connection to the pi working via setting up a dhcp server on my laptop on a separate subnet from the subnet the router is on. 

This method has the adantage that it requires no modification of the network config settings on the pi to work (and so less possible discrepancies). 

I added documentation for how to set it up here. Since it requires no modifications of the pi, I was thinking it makes more sense to just live as a file here in devdocs than as part of the peach-config readme.

### CODE REVIEW

**Comment by mhfowler** [comment]
Commit e67849a can actually be reverted as that was about syncing peach-config docs.

**Comment by mycognosist** [comment]
@mhfowler 

The instructions all look good to me. Really cool that you found a way to do it without changing Pi config!

I'm a stickler for documentation consistency so I've modified the formatting of your document to match the rest of the devdocs (mostly things like headings, bold, italics etc.).

I agree that it makes sense to place this doc in devdocs. I think it might also be a good idea to replicate it in `peach-config/docs/`. Even though it doesn't involve changing settings on the Pi, I can imagine a future scenario where another dev is deploying their setup using `peach-config` and wants to create a direct ethernet connection. In that scenario, it might be helpful if the doc was right there in devdocs (I think there's less of a chance of a dev digging through the devdocs to find something). This doc is unlikely to change over time so we're not adding a lot of maintenance overhead by having it in two locations.

In terms of placement within devdocs, I think the best fit might be in Software -> Operating System -> Networking -> Direct Ethernet Setup (rather than directly in the Software section).

If you agree with the change of placement, you're welcome to merge the PR once you've made that change and bumped the version of devdocs in the `README` 🙏🏻

**Comment by mhfowler** [comment]
@mycognosist  I feel you about consistency, thanks for the updates.

Quick question: 
when you say Software -> Operating System -> Networking -> Direct Ethernet
... do you mean creating a folder "Networking", and putting the current networking.md and direct-ethernet-setup.md in that the folder?
or just putting this as a subsection of networking.md?

**Comment by mycognosist** [comment]
@mhfowler 

Good question. Hmm...maybe let's add it as a subsection of `networking.md` rather than creating an extra folder. The current doc isn't very long so I think it makes sense to keep it all on one page.

I'll need to update the current info in `networking.md` to reflect the switch to `systemd-networkd`. I can do that as a separate PR once this is merged.

**Review by mycognosist — APPROVED** [review]

**Comment by mhfowler** [comment]
Ok sounds good, put it as a subsection and merged it

**Pull request merged**
